import About from '@/components/base/About'
import Education from '@/components/base/Education'
import Expectations from '@/components/base/Expectations'
import Experience from '@/components/base/Experience'
import Home from '@/components/base/Home'
import Layout from '@/components/base/Layout'
import Skills from '@/components/base/Skills'
import Head from 'next/head'

export default function Index() {

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <Home />
          <About />
          <Skills />
          <Experience />
          <Education />
          <Expectations />
        </Layout>
      </main>
    </>
  )
}
